plugins {
    id 'java-library'
    id 'maven-publish'
}

group = "git.artdeell"
version = "1.0.0"

configurations.default.setCanBeResolved(true)

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8

    withSourcesJar()
    withJavadocJar()
}

jar {
    manifest {
        attributes("Manifest-Version": "1.0")
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}